### ISSUE TITLE
Can add movement speed modifications and skills without CD

### ISSUE THREAD

**Issue by Zk1oo** [asd9176506911298/Goose-Goose-Duck-ImGui#1]
Can add movement speed modifications and skills without CD

**Comment by asd9176506911298** [comment]
movement speed obfuscate
I need to research

**Comment by Zk1oo** [comment]
You can try to add a box drawing for other players

**Comment by Zk1oo** [comment]
Accelerate directly with Initial 5 Soul 7.5 to search back and forth

**Comment by Zk1oo** [comment]
Use CE

**Comment by asd9176506911298** [comment]
https://github.com/asd9176506911298/Goose-Goose-Duck-ImGui/releases/tag/v0.0.3
Only Test on Tutorial Mode

**Comment by asd9176506911298** [comment]
> You can try to add a box drawing for other players

https://github.com/asd9176506911298/Goose-Goose-Duck-ImGui/releases/tag/v0.0.5
